### ISSUE TITLE
User stories + Wireframes

### ISSUE THREAD

**Issue by nickai** [expense-manager/expense-manager#1]
Hi Zhaolong + Zekun...Going forward, can you please create a GitHub issue when you are ready to submit your group milestone? I also don't see a link to your wireframes.

Remember that by the end of your second sprint, we expect each team to have their core flows functionally complete (but rough) so this week your team should complete the first 50% of your core functionality.

While building this app, try to keep in your mind the story for your app and what you need to have a polished demo. Be aggressive about which features you can scope into the first version for demo day. Excited to see what your group comes up with! Let us know what we can do to help.

**Comment by ZekunWang** [comment]
Hi Nick,

Here is the link for the wireframes:
https://drive.google.com/drive/u/0/folders/0BwTA9B8hBSv0V3l0WnZxMWtoNjA

Thanks,
Zekun Wang

**Comment by nickai** [comment]
Looks like I don't have access. Can you make sure nick@codepath.com, nathan@codepath.com, vibhor@codepath.com, and prerak@codepath.com all have access? Thanks!

**Comment by ZekunWang** [comment]
Hi,

I just shared link with all the emails you provide. Can you try again and
take a look at the wireframes?

Thanks,
Zekun

**Comment by nickai** [comment]
👍 ...great job on the wireframes...these will be a huge help as you build out your app.
